[package]
name = "taskclaw"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
log = "0.4"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
uuid = { version = "1.17.0", features = ["v7", "serde"] }

[dev-dependencies]
tempfile = "3.10.1"
