name: Update Homebrew Formula

on:
  release:
    types: [published]

jobs:
  update-homebrew:
    name: Update Homebrew Formula
    runs-on: ubuntu-latest
    if: "!github.event.release.prerelease"
    steps:
    - name: Update Homebrew formula
      uses: dawidd6/action-homebrew-bump-formula@v3
      with:
        token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
        tap: yourusername/homebrew-tap
        formula: claw
        tag: ${{ github.event.release.tag_name }}
        revision: ${{ github.sha }}
        force: false

  update-formula-manually:
    name: Generate Formula (Manual)
    runs-on: ubuntu-latest
    if: "!github.event.release.prerelease"
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Calculate SHA256 for macOS binary
      run: |
        MACOS_URL="https://github.com/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }}/claw-macos-x86_64.tar.gz"
        SHA256=$(curl -sL "$MACOS_URL" | sha256sum | cut -d' ' -f1)
        echo "MACOS_SHA256=$SHA256" >> $GITHUB_ENV

    - name: Generate Homebrew formula
      run: |
        mkdir -p homebrew-formula
        cat > homebrew-formula/claw.rb << EOF
        class Claw < Formula
          desc "A simple CLI task tracking tool"
          homepage "https://github.com/${{ github.repository }}"
          version "${{ github.event.release.tag_name }}"
          license "MIT"

          on_macos do
            if Hardware::CPU.intel?
              url "https://github.com/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }}/claw-macos-x86_64.tar.gz"
              sha256 "${{ env.MACOS_SHA256 }}"
            else
              url "https://github.com/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }}/claw-macos-arm64.tar.gz"
              sha256 "PLACEHOLDER_ARM64_SHA256"
            end
          end

          on_linux do
            url "https://github.com/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }}/claw-linux-x86_64.tar.gz"
            sha256 "PLACEHOLDER_LINUX_SHA256"
          end

          def install
            bin.install "claw"
            
            # Install man page
            man1.install "man/claw.1" if File.exist?("man/claw.1")
            
            # Install completions
            if Dir.exist?("completions")
              bash_completion.install "completions/claw.bash" => "claw"
              zsh_completion.install "completions/_claw" => "_claw"  
              fish_completion.install "completions/claw.fish" => "claw.fish"
            end
          end

          test do
            assert_match version.to_s, shell_output("#{bin}/claw --version")
            
            # Test basic functionality
            system "#{bin}/claw", "add", "test task"
            output = shell_output("#{bin}/claw list")
            assert_match "test task", output
          end
        end
        EOF

    - name: Upload formula as artifact
      uses: actions/upload-artifact@v4
      with:
        name: homebrew-formula-${{ github.event.release.tag_name }}
        path: homebrew-formula/claw.rb